import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import NavBar from "@/components/NavBar";
import { Toaster } from "@/components/ui/toaster";

import AuthContext from "@/features/auth/contexts/AuthContext";

import { cn } from "@/libs/utils";

import "./globals.css";

const fontSans = Open_Sans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex min-h-dvh flex-col bg-neutral-200 font-sans antialiased",
          fontSans.variable,
        )}
      >
        <AuthContext>
          <NavBar />
          <main className="mx-auto flex w-full max-w-sm flex-1 flex-col items-center bg-neutral-100">
            {children}
          </main>
          <Toaster />
        </AuthContext>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
