import AuthContext from "@/context/AuthContext";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import { cn } from "@/lib/utils";

import "./globals.css";

const fontSans = Open_Sans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-neutral-100 font-sans antialiased",
          fontSans.variable,
        )}
      >
        <AuthContext>
          <main className="mx-auto flex min-h-dvh max-w-sm flex-col items-center justify-between rounded-lg bg-white p-4">
            {children}
          </main>
        </AuthContext>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
